version: 2.1

orbs:
  maven: circleci/maven@1.4.0
  circleci-maven-release-orb: sonatype-nexus-community/circleci-maven-release-orb@0.0.18

release-args: &release-args
  mvn-release-perform-command: mvn --batch-mode release:perform -s .circleci/.maven.xml -PbuildKar,circle-ci-release
  ssh-fingerprints: "51:27:e7:c8:f3:e4:31:81:f2:76:50:db:08:7e:90:87"
  context: rso-base
  filters:
    branches:
      only: main

jobs:
  build_and_test:
    docker:
      - image: 'cimg/openjdk:8.0'
    steps:
      - checkout
      - maven/with_cache:
          verify_dependencies: false
          steps:
            - run:
                name: Run Maven Build
                command: |
                  mvn clean --batch-mode verify -PbuildKar -Dit
      - run:
          name: Save test results
          command: |
            mkdir -p ~/project/artifacts/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/project/artifacts/junit/ \;
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/project/artifacts/junit/ \;
            mkdir -p ~/project/artifacts/it-reports/
            find . -type f -regex ".*/target/it-reports/.*" -exec cp {} ~/project/artifacts/it-reports/ \;
          when: always
      - store_test_results:
          path: ~/project/artifacts/junit
      - store_artifacts:
          path: ~/project/artifacts/it-reports

workflows:
  build-branch:
    jobs:
      - build_and_test:
          filters:
            branches:
              ignore: main
          pre-steps:
            - run:
                command: |
                  while true; do
                    sleep 5
                    ps auxwwf
                    echo "======"
                  done
                background: true
          post-steps:
            - run:
                command: cat /sys/fs/cgroup/memory/memory.max_usage_in_bytes
                when: always

  run-release:
    jobs:
      - approve-release:
          type: approval
          filters:
            branches:
              only: main
      - circleci-maven-release-orb/run-maven-release:
          requires:
            - approve-release
          <<: *release-args

  release-from-main:
    jobs:
      - build_and_test:
          filters:
            branches:
              only: main
      - circleci-maven-release-orb/run-maven-release:
          requires:
            - build_and_test
          <<: *release-args
